---
 - name: implement nfs server
   hosts: ip-172-31-47-39.ap-south-1.compute.internal
   gather_facts: no
   tasks:

    - name: install nfs software
      dnf:
       name: nfs-utils
       state: present

    - name: start and enable nfs service
      service:
       name: nfs-server
       state: started
       enabled: yes

    - name: create a share directory
      file:
       path: /share101
       state: directory
      tags: create

    - name: make share configuration
      lineinfile:
       path: /etc/exports
       line: '/share101 ip-172-31-41-129.ap-south-1.compute.internal(ro)'
      notify: update the service
      tags: create
  
   handlers:
   
    - name: update the service
      shell: 
       cmd: exportfs -rv
...