apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: us-west-2
  version: "1.25"

managedNodeGroups:
  - name: ng-1
    instanceType: m5.large
    labels: { role: workers }
    desiredCapacity: 2
    volumeSize: 20
    privateNetworking: true
